#!/usr/bin/env python3
"""Generates data/THIRD_PARTY_LICENSES.txt and
src/app/axthirdparty_generated.h from the Conan dependency graph.

Both files are derived, checked-in artifacts (like axabout_wdr.cpp).
Rerun this after changing conanfile.py's requirements:

    python3 tools/generate_third_party_notices.py

The graph is resolved against the lockfiles in conan-locks/, not live
against Conan Center, so this is fully reproducible: an unrelated
recipe getting a new revision upstream (e.g. expat 2.8.4 -> 2.8.5)
can't change the output between two runs. If conanfile.py's
requirements actually changed, refresh the lockfiles first:

    python3 tools/generate_third_party_notices.py --refresh-lockfiles

Requires `conan` on PATH; only resolves the dependency graph (no
building), so it works even without a local Conan cache of built
binaries.
"""
import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCKS_DIR = ROOT / "conan-locks"

# aruspix is the root package, not a third party. doctest only links
# into the test binaries (aruspix_tests, aximage_loadfile_tests,
# imregister_integration_tests), never into the shipped `aruspix`
# executable, so it has no place in end-user credits.
EXCLUDE_NAMES = {"aruspix", "doctest"}

# Windows and macOS resolve to the same graph because wxWidgets uses
# their native GUI backends there; Linux additionally pulls in the
# GTK/X11/Wayland stack via wxWidgets' GTK backend.
PLATFORMS = {
    "Linux": {"settings": {"os": "Linux", "arch": "x86_64"}, "lockfile": LOCKS_DIR / "linux.lock"},
    "Windows": {"settings": {"os": "Windows", "arch": "x86_64"}, "lockfile": LOCKS_DIR / "windows.lock"},
    "macOS": {"settings": {"os": "Macos", "arch": "armv8"}, "lockfile": LOCKS_DIR / "macos.lock"},
}


def refresh_lockfile(settings, lockfile):
    args = ["conan", "lock", "create", str(ROOT), f"--lockfile-out={lockfile}"]
    for key, value in settings.items():
        args += ["-s", f"{key}={value}"]
    print(f"refreshing {lockfile}...", file=sys.stderr)
    subprocess.run(args, check=True, capture_output=True, text=True)


def conan_graph(settings, lockfile):
    args = ["conan", "graph", "info", str(ROOT), "--format=json", f"--lockfile={lockfile}"]
    for key, value in settings.items():
        args += ["-s", f"{key}={value}"]
    result = subprocess.run(args, capture_output=True, text=True, check=True)
    return json.loads(result.stdout)


def host_dependencies(graph):
    """Packages actually linked into the shipped binary: host context
    (as opposed to build-only tools like cmake/ninja/m4), excluding
    Conan's "system" stubs (detected on the build machine, e.g. system
    X11/OpenGL dev headers -- not vendored or shipped by us)."""
    deps = {}
    for node in graph["graph"]["nodes"].values():
        name = node.get("name")
        if not name or name in EXCLUDE_NAMES:
            continue
        if node.get("context") != "host":
            continue
        if node.get("version") == "system":
            continue
        license_ = node.get("license")
        if isinstance(license_, list):
            license_ = " / ".join(license_)
        deps[name] = (node.get("version"), license_ or "unknown")
    return deps


def format_entry(name, version, license_):
    return f"{name} {version} ({license_})"


def write_licenses_txt(per_platform):
    lines = [
        "Aruspix third-party dependencies",
        "=================================",
        "",
        "Generated by tools/generate_third_party_notices.py from the Conan",
        "dependency graph (conanfile.py). Do not edit by hand -- rerun the",
        "script after changing dependencies instead.",
        "",
        "Each package below is linked into the aruspix binary on the",
        "listed platform(s) and is redistributed as part of the Aruspix",
        "download for that platform, under the license shown.",
        "",
    ]
    for platform, deps in per_platform.items():
        lines.append(platform)
        lines.append("-" * len(platform))
        for name in sorted(deps, key=str.lower):
            version, license_ = deps[name]
            lines.append(f"  {format_entry(name, version, license_)}")
        lines.append("")
    out = ROOT / "data" / "THIRD_PARTY_LICENSES.txt"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")


def write_credits_header(per_platform):
    def credits_string(deps):
        entries = [format_entry(name, *deps[name]) for name in sorted(deps, key=str.lower)]
        return ";".join(entries)

    windows_mac = credits_string(per_platform["Windows"])
    linux = credits_string(per_platform["Linux"])

    header = f"""// Generated by tools/generate_third_party_notices.py from the Conan
// dependency graph (conanfile.py). Do not edit by hand -- rerun the
// script after changing dependencies instead.

#ifndef __AXTHIRDPARTY_GENERATED_H__
#define __AXTHIRDPARTY_GENERATED_H__

#if defined(__WXMSW__) || defined(__WXMAC__)
#define THIRD_PARTY_CREDITS "{windows_mac}"
#else
#define THIRD_PARTY_CREDITS "{linux}"
#endif

#endif
"""
    out = ROOT / "src" / "app" / "axthirdparty_generated.h"
    out.write_text(header, encoding="utf-8")
    print(f"wrote {out}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--refresh-lockfiles",
        action="store_true",
        help="Re-resolve conan-locks/*.lock against Conan Center first "
        "(only needed after changing conanfile.py's requirements).",
    )
    args = parser.parse_args()

    per_platform = {}
    for platform, config in PLATFORMS.items():
        if args.refresh_lockfiles:
            refresh_lockfile(config["settings"], config["lockfile"])
        print(f"resolving Conan graph for {platform}...", file=sys.stderr)
        graph = conan_graph(config["settings"], config["lockfile"])
        per_platform[platform] = host_dependencies(graph)

    write_licenses_txt(per_platform)
    write_credits_header(per_platform)


if __name__ == "__main__":
    main()
